export interface KnowledgeItem {
  category: string;
  keywords: string[];
  content: string;
}

export const NEXORA_KNOWLEDGE: KnowledgeItem[] = [
  {
    category: "Dashboard",
    keywords: ["dashboard", "home", "readiness score", "confidence score", "missions", "metrics"],
    content: "The Nexora Dashboard displays business health metrics. The 'Business Readiness Score' indicates how ready the business is for expansion. The 'Growth Confidence Score' measures data completeness and reliability of recommendations. It also presents daily pending missions and active customer alerts."
  },
  {
    category: "Customer Analytics",
    keywords: ["customer", "analytics", "segments", "clv", "lifetime value", "repeat customer", "churn", "slipping"],
    content: "Customer Analytics in Nexora analyzes customer cohorts, repeat customer rates, average order values, and churn. It segments clients into new, active VIPs, slipping buyers (no purchase in 30-60 days), and inactive clients (no purchase in 60+ days) to help re-engage quiet customer accounts."
  },
  {
    category: "Growth Missions",
    keywords: ["missions", "mission", "tasks", "priority", "action items", "reasoning"],
    content: "Growth Missions are dynamically generated, high-leverage business tasks (up to 5) created by Nexora's AI. They prioritize specific growth actions based on your latest sales ledger trend and digital visibility metrics."
  },
  {
    category: "Insights",
    keywords: ["insights", "insight", "narrative", "trends", "visibility", "performance"],
    content: "Nexora Insights generates daily narrative story lines analyzing your business's revenue trajectory, customer loyalty changes, and digital maturity gaps compared to industry best practices."
  },
  {
    category: "Automation",
    keywords: ["automation", "templates", "drafts", "whatsapp", "email", "reminder", "slipping customers"],
    content: "The Automation hub drafts template messages (WhatsApp/email/reminders) targeting inactive or slipping customer segments. Business owners review and approve these drafts before triggering actual re-engagement."
  },
  {
    category: "Reports",
    keywords: ["reports", "report", "csv", "ledger", "upload"],
    content: "Reports are structured AI intelligence summaries and revenue forecasting ledgers generated from customer lists or sales CSV uploads."
  },
  {
    category: "Navigation & Features",
    keywords: ["menu", "navigation", "routes", "sidebar", "drawer", "hamburger"],
    content: "Users can navigate Nexora using a responsive side drawer sidebar containing routes to Dashboard, Customer Analytics, AI Chat, Growth Missions, Insights, Automation, and Settings."
  },
  {
    category: "Business Terminology",
    keywords: ["terminology", "jargon", "what is clv", "churn rate"],
    content: "CLV (Customer Lifetime Value) is the total cumulative revenue generated by a single customer profile. Churn indicates the rate at which customers stop buying. Slipping customers are those inactive between 30 to 60 days."
  }
];
